# Generated by Django 3.2.6 on 2021-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightRegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='trip_category',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Round Way', 'Round Way')], default=None, max_length=50),
        ),
    ]
